# Generated by Django 5.0.6 on 2024-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_white_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color_black_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color_red_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
